# Generated by Django 3.0.2 on 2020-01-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '产品标签',
                'verbose_name_plural': '产品标签',
                'db_table': 'cms_product_tag',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_tag',
            field=models.ManyToManyField(blank=True, db_table='cms_product_product_tag', null=True, related_name='tags', to='products.ProductTag', verbose_name='产品标签'),
        ),
    ]
