# Generated by Django 3.0.2 on 2020-01-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['order_num', '-create_at'], 'verbose_name': '产品', 'verbose_name_plural': '产品'},
        ),
        migrations.AlterModelOptions(
            name='skutype',
            options={'ordering': ['-id'], 'verbose_name': '产品类型', 'verbose_name_plural': '产品类型'},
        ),
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(max_length=120, verbose_name='产品名'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '编辑中'), (1, '已上架'), (2, '已下架')], default=0, verbose_name='兑换产品状态'),
        ),
    ]
