# Generated by Django 3.0.2 on 2020-01-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200116_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tag',
            field=models.ManyToManyField(blank=True, db_table='cms_product_product_tag', related_name='tags', to='products.ProductTag', verbose_name='产品标签'),
        ),
    ]
