# Generated by Django 3.0.2 on 2020-01-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200117_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['level', 'order_num', 'id'], 'verbose_name': '产品类型', 'verbose_name_plural': '产品类型'},
        ),
        migrations.AddField(
            model_name='producttype',
            name='order_num',
            field=models.IntegerField(default=10000, verbose_name='排序值[越小越靠前]'),
        ),
    ]
