#!/bin/bash

python manage.py migrate
# python manage.py runserver_plus 0.0.0.0:8000
# python manage.py runserver 0.0.0.0:8000

gunicorn -c /app/compose/dev/django/gunicorn.py server.wsgi:application
