# Generated by Django 3.0.2 on 2020-01-15 13:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cfg.SiteModule')),
            ],
            options={
                'verbose_name': '站点模块',
                'verbose_name_plural': '站点模块',
                'db_table': 'cms_site_module',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='标题')),
                ('cover', models.ImageField(upload_to='', verbose_name='封面图')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '编辑中'), (1, '已发布'), (2, '已撤回')], default=0, verbose_name='状态')),
                ('is_recommand', models.BooleanField(default=False, verbose_name='推荐')),
                ('site_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfg.SiteModule', verbose_name='站点模块')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'cms_article',
                'ordering': ['-id'],
            },
        ),
    ]
