# Generated by Django 3.0.2 on 2020-01-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.CharField(default='', max_length=500, verbose_name='简介'),
        ),
    ]
