# Generated by Django 3.0.2 on 2020-01-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='标题')),
                ('cover', models.ImageField(upload_to='', verbose_name='封面图')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '编辑中'), (1, '已发布'), (2, '已撤回')], default=0, verbose_name='状态')),
                ('site_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfg.SiteModule', verbose_name='站点模块')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'cms_article',
                'ordering': ['-id'],
            },
        ),
    ]
