# Generated by Django 3.0.2 on 2020-01-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('cfg', '0002_article_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='', verbose_name='封面图')),
                ('order_num', models.IntegerField(default=10000, verbose_name='排序值[越小越靠前]')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfg.Article', verbose_name='文章')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '首页轮播',
                'verbose_name_plural': '首页轮播',
                'db_table': 'cms_index_item',
                'ordering': ['order_num', '-id'],
            },
        ),
    ]
