# Generated by Django 3.0.2 on 2020-01-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_recommand',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
    ]
