# Generated by Django 3.0.2 on 2020-04-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0003_indexitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='文章链接'),
        ),
    ]
