# Generated by Django 3.0.2 on 2020-01-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200116_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(max_length=200, upload_to='', verbose_name='头像'),
        ),
    ]
