# Generated by Django 3.0.2 on 2020-01-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200117_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', max_length=200, upload_to='', verbose_name='头像'),
        ),
    ]
